### ISSUE TITLE
Allow reuse of existing aliases with :jvm-opts 

### ISSUE THREAD

**Issue by jeroenvandijk** [seancorfield/polylith-external-test-runner#11]
I'm just migrating from the default test-runner of Polylith to this one. Thank you very much for creating it. It has been a big time saver already!

The migration is pretty straight forward. One thing that I think could be improved is to allow the reuse of existing aliases for `:jvm-opts:`. Let me illustrate this with an example. I'm using Datalevin that requires special `:jvm-opts` so I already have an alias in my `deps.edn` for this. It would be nice if could reuse that somehow.

Right now I have something like this in my `deps.edn`
```clojure
{:aliases
 {:jvm-base {:jvm-opts ["--add-opens=java.base/java.nio=ALL-UNNAMED"
                        "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"]}
  :poly-jvm-opts ["--add-opens=java.base/java.nio=ALL-UNNAMED"
                  "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"]                 
  :poly {:jvm-opts ["-Dpoly.test.jvm.opts=:poly-jvm-opts"]}}}
```

I think it would be nice if it could be something like:

```clojure
{:aliases
 {:jvm-base {:jvm-opts ["--add-opens=java.base/java.nio=ALL-UNNAMED"
                        "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"]}

  :poly {:jvm-opts ["-Dpoly.test.jvm.opts=:jvm-base"]}}}
```

What do you think? I can make a PR for it if you think it is an improvement.

**Comment by seancorfield** [comment]
Interesting. I hadn't considered that use case. That should be fairly straightforward to add support for and I agree it would be reasonable to do so. Docs and tests will need updating a bit too.

I can take it on later this week, unless you get to a PR before then.

**Comment by seancorfield** [comment]
This has allowed for a nice simplification at work -- thank you for suggesting it!

**Comment by jeroenvandijk** [comment]
Happy to hear that - thank you  for the change!
