### ISSUE TITLE
Test runner fails when no java opts are specified

### ISSUE THREAD

**Issue by lread** [seancorfield/polylith-external-test-runner#4]
While helping out with editing poly docs, I decided to give the external test runner a whirl.

Working from the poly `example` tutorial project, if I configure the external test runner as described in the README and then run:

```
clojure -M:poly test
```

I get:
```
Projects to run tests from: command-line

Could not create valid test runner for the command-line project: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```

The fact that poly is swallowing the stack trace doesn't help much, but I found if I provide some java opts:
```
POLY_TEST_JVM_OPTS=-Dfoo.bar=true clojure -M:poly test
```

All seems good:
```
Projects to run tests from: command-line

Running tests for the command-line project using test runner: Polylith org.corfield.external-test-runner...
Running tests from the command-line project, including 2 bricks: user, cli

Testing se.example.cli.core-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Testing se.example.user.interface-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Execution time: 1 seconds
```

Seems like the current code might be assuming java opts are always set?
https://github.com/seancorfield/polylith-external-test-runner/blob/5a4518dd310daa5ccf592047d3e770df1c375f2b/components/external-test-runner/src/org/corfield/external_test_runner/core.clj#L107

**Comment by seancorfield** [comment]
Nice catch! I've never run it without at least some JVM options... oops!

**Comment by seancorfield** [comment]
Try:
```clojure
io.github.seancorfield/polylith-external-test-runner
{:git/tag "v0.3.0" :git/sha "9f6391a"
 :deps/root "projects/runner"}
```

**Comment by lread** [comment]
Thanks @seancorfield, 0.3.0 fixes the issue for me!
